version: '3.8'

services:
  haproxy:
    image: haproxy:2.8-alpine
    container_name: haproxy-lb
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:8080" # Frontend
      - "8404:8404" # Stats
      - "127.0.0.1:9999:9999" # Runtime API (safe for local lab)
    depends_on:
      - web-v1-a
      - web-v1-b
      - web-v2-canary

  web-v1-a:
    image: nginx:1.25-alpine
    container_name: web-v1-a
    volumes:
      - ./web/v1-a:/usr/share/nginx/html:ro

  web-v1-b:
    image: nginx:1.25-alpine
    container_name: web-v1-b
    volumes:
      - ./web/v1-b:/usr/share/nginx/html:ro

  web-v2-canary:
    image: nginx:1.25-alpine
    container_name: web-v2-canary
    volumes:
      - ./web/v2-canary:/usr/share/nginx/html:ro
